### ISSUE TITLE
javascript support?

### ISSUE THREAD

**Issue by dkati** [SatAgro/fieldclimate#9]
good evening. i didnt manage to make javascript fetch data from the API.
any chance to make it work ?

For now , i got this code:

```

	var pub_key = "xxx";
        var priv_key = "yyy";
 	  
	var dateStamp = "Fri, 03 Jan 2020 21:57:10 GMT";
	var content = "GET"+"/user"+dateStamp+pub_key;
	var hash = CryptoJS.HmacSHA256(content, priv_key);
	//var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

	var tmpstr=hash+"";

	var authStr =  "hmac " + pub_key +":" + tmpstr;
      let API_LINK = "https://api.fieldclimate.com/v1/user";
	console.log("=============");
	console.log("hmac "+pub_key+":"+tmpstr);
      fetch(API_LINK, {
        method: "GET",
        headers: {
		"Accept":"application/json",
		"Authorization":authStr
		
	}
      })
       //response => response.ok ? response.json() : Promise.reject(response)
      .then(response => {console.log(response)})
      .then(data => {console.log(data)})
      .catch( error => {console.log(error)})
	
```

But i get 401 response code :/

**Comment by gaazkam** [comment]
This is an issue tracker of a Python library communicating with the Fieldclimate API, not of the Fieldclimate API itself. I know nothing more about this API than you.

Having said that, skimming over your code reveals you may have forgotten about the mandatory `Date` header.

**Comment by dkati** [comment]
u cant append "date" to headers..its a forbidden "date" header to be added via browser

**Comment by gaazkam** [comment]
Is the datestamp your browser sends in the user agent controlled date header precisely equal to the one you are hardcoding?

I'm not certain what may the problem with your JS code be but the way I understand the upstream Fieldclimate docs it is required that the date header and the timestamp used to create the authorization header are the same. Beyond that suggestion, which may or may not be correct, I can't really say much more.
